# /**************************************
#  ecmh - Easy Cast du Multi Hub
#  by Jeroen Massar <jeroen@unfix.org>
# ***************************************
# $Author: bruce.chang $
# $Id: //WIFI_SOC/release/SDK_4_1_0_0/source/user/ecmh/tools/Makefile#1 $
# $Date: 2012/09/28 $
# **************************************/
#
# Tools Makefile
#

all:	mtrace6

mtrace6: mtrace6/
	$(MAKE) -C mtrace6 all

clean:
	$(MAKE) -C mtrace6 clean

# Mark targets as phony
.PHONY : all clean mtrace6

