#
# Makefile for plugins on Solaris 2
#
# $Id: //WIFI_SOC/release/SDK_4_1_0_0/source/user/ppp-2.4.1/pppd/plugins/Makefile.sol2#1 $
#

include ../../svr4/Makedefs

CFLAGS	= -c -O -I.. -I../../include $(COPTS)
LDFLAGS	= -G 

all:	minconn.so

minconn.so: minconn.o
	ld -o $@ $(LDFLAGS) -h $@ minconn.o

minconn.o: minconn.c
	$(CC) $(CFLAGS) -c $? 

passprompt.so: passprompt.o
	ld -o $@ $(LDFLAGS) -h $@ passprompt.o

passprompt.o: passprompt.c
	$(CC) $(CFLAGS) -c $?

clean:
	rm -f *.o *.so
